### ISSUE TITLE
Screenshot within C/C++ (clangd) buffer breaks lsp server (Invalid Parameters)

### ISSUE THREAD

**Issue by Jake-Moss** [tecosaur/screenshot#10]
Taking a screenshot within a `C/C++` buffer with lsp enabled (clangd) breaks the lsp server on copy/save. It does not break if the screenshot is aborted.

`*Messages*` reports
```
Screenshot copied
Error in post-command-hook (winner-save-old-configurations): (wrong-type-argument frame-live-p #<dead frame  0x56548eef4ac0>)
LSP :: Error from the Language Server: onCodeAction called for non-added file (Invalid Parameters)
LSP :: Error from the Language Server: trying to get AST for non-added document (Invalid Parameters)
LSP :: Error from the Language Server: onCodeAction called for non-added file (Invalid Parameters)
LSP :: Error from the Language Server: trying to get AST for non-added document (Invalid Parameters)
```
This is fixed by reverting the buffer/restarting the server.

This does not occur within a python (pyright) buffer.

I am up to date with DOOM and screenshot.el, running `emacs-pgtk-native-comp`.
Using `clangd version 12.0.1`

Edit:
Setting values such as `Maximum width` using `-W` also triggers this.

**Comment by tecosaur** [comment]
Interesting. I'm pretty tight on time ATM but I should be able to take a look eventually:tm:.

**Comment by tecosaur** [comment]
I've done some hook tweaks recently, if you could check again that would be good.

**Comment by Jake-Moss** [comment]
Unfortunately I'm still able to reproduce this when copying/saving.

Setting values such as the `Maximum width` no longer cause this.

Doom version (Latest)
```
GNU Emacs     v28.2            nil
Doom core     v3.0.0-pre       HEAD -> master 9f22a0a2a 2022-10-07 19:48:23 +0200
Doom modules  v22.10.0-pre     HEAD -> master 9f22a0a2a 2022-10-07 19:48:23 +0200
```
`M-x doom/describe-package screenshot` 
```
    Package: screenshot
     Source: Straight
     Pinned: unpinned
      Build: HEAD -> master, replaced, origin/master, origin/HEAD 9653754 2022-10-18 02:45:30 +0800
             Build location: ~/.emacs.d/.local/straight/build-28.2/screenshot/
             Repo location: ~/.emacs.d/.local/straight/repos/screenshot/
     Recipe: (:host github :repo "tecosaur/screenshot" :build
              (:not compile)
              :package "screenshot" :type git :local-repo "screenshot")
                Homepage: https://github.com/tecosaur/screenshot
    Modules: Declared by the following Doom modules:
             :user  (no readme)
             :user modules (no readme)
    Configs: This package is not configured anywhere
```
```
$ clangd --version
clangd version 14.0.5 (Fedora 14.0.5-1.fc36)
Features: linux
Platform: x86_64-unknown-linux-gnu; target=x86_64-redhat-linux-gnu
```

I'll attempt to reproduce this in vanilla emacs tonight, but I have no related config for `lsp-mode`, `clangd`, or `screenshot`.

**Comment by tecosaur** [comment]
Hmm, so we're only partway to a fix. If I knew more about *how* those LSP commands were being triggered that would be rather helpful.

**Comment by Jake-Moss** [comment]
I've been able to reproduce it using this config, and have capture the lsp io log, although it doesn't look particularly insightful. The screenshot was taken around like 590 (Before the first `trying to get AST for non-added document`). Also if you'd like let me know and I'll mention you somewhere!
```lisp
;;; init.el --- Description -*- lexical-binding: t; -*-

;; Bootstrap straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; Install use-package
(straight-use-package 'use-package)

(setq straight-use-package-by-default t)

(use-package lsp-mode
  :init
  ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
  (setq lsp-keymap-prefix "C-c l")
  :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
         (c-mode . lsp))
  :commands lsp)

(use-package screenshot
  :straight (:host github :repo "tecosaur/screenshot" :build (:not compile)))

(setq lsp-log-io t)
```
`M-x lsp-workspace-show-log`
https://pastebin.com/f2AQtF8V

**Comment by tecosaur** [comment]
I'm guessing that the LSP stuff gets triggered by some hook, and so the fix would be to bind that hook to `nil` temporarily. Looking at the log, I'm slightly confused as I see:
```json
  "textDocument": {
    "uri": "file:///tmp/test/testing.c"
  },
```
both before and after the `trying to get AST for non-added document` error, so I'm not sure what the change causing the issue is.

BTW, due to recent fixes to longstanding issues, you should be able to do away with `:build (:not compile)` now :slightly_smiling_face:

**Comment by Jake-Moss** [comment]
Heres the clangd verbose out I was able to get with 
```lisp
(add-to-list 'lsp-clients-clangd-args "--log=verbose")
```
https://pastebin.com/tBmQZZ6A

Interestingly it seems `lsp-mode` is sending
```
V[19:29:25.794] <<< {"jsonrpc":"2.0","method":"textDocument/didClose","params":{"textDocument":{"uri":"file:///tmp/test/testing.c"}}}

I[19:29:25.794] <-- textDocument/didClose
I[19:29:25.794] --> textDocument/publishDiagnostics
V[19:29:25.794] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///tmp/test/testing.c"}}
```
Which indicates this comment might be relevant

> The editor tells clangd which files are open/closed, and clangd only supports operating on files that are open. That error message is what you get if the file has not been opened, or has been opened and then closed[1].
>
>I think it's extremely likely this is an editor/client bug, a full clangd log including the textDocument/didOpen and textDocument/didClose messages (with clangd --log=verbose) would be the way to tell for sure.
>
>    As far as I remember, I dragged a tab with this file from one "focus group" to another, then it stopped working
>
> My guess is that the way the sublime LSP plugin translates internal events into LSP notifications is not handling this case really well. Ideally, it would not send any open/close events. Closing and reopening the document, in that order, would also work. But if a new open event is sent before the close event, then clangd will see the sequence "open(ok) ... open(error: already open) close(ok) documentHighlight(error: not open)".

https://github.com/clangd/clangd/issues/609#issuecomment-735379720

> BTW, due to recent fixes to longstanding issues, you should be able to do away with :build (:not compile) now slightly_smiling_face

Great to hear!

I've also run into some issues with very short screenshots (2 lines) and long buffers (no wrapping) but I'll mention them in #7

**Comment by tecosaur** [comment]
Hmm, so perhaps killing the indirect buffer is telling the LSP server that the document has been closed? Can you try with text mode? (`-t`)

**Comment by Jake-Moss** [comment]
With `-t` it functions as expected! Although suffering the issues I mentioned in #7
![image](https://user-images.githubusercontent.com/49361082/196400306-780a23a9-f4b5-48f9-9daa-d7459677fd10.png)

**Comment by tecosaur** [comment]
Ok, so it's definitely a buffer hook then. Could you let me know the value of `kill-buffer-hook` in the buffer?

**Comment by Jake-Moss** [comment]
Sure thing, in the vanilla config it is
```lisp
(flymake-kill-buffer-hook lsp--text-document-did-close t)
```
And using Doom its
```lisp
(lsp--text-document-did-close flycheck-teardown t)
```

**Comment by tecosaur** [comment]
Thanks! The `lsp--text-document-did-close` entry looks like a likely cause of the issues. I'll see if I can bind `kill-buffer-hook` to nil.

**Comment by Jake-Moss** [comment]
As very rudimentary confirmation, removing it manually from the hook solves this issue.

**Comment by tecosaur** [comment]
Can you try d6ced66507bc04575b8b8eb84b7ff55f5fcf599e ?

**Comment by Jake-Moss** [comment]
Unfortunately that doesn't solve it in either vanilla or Doom

**Comment by Jake-Moss** [comment]
What about `make-indirect-buffer` with `INHIBIT-BUFFER-HOOKS` as `t`? Something like
```lisp
(defun screenshot--narrowed-clone-buffer (beg end)
  "Create a clone of the current buffer, narrowed to the region from BEG to END.
This buffer then then set up to be used for a screenshot."
  (let ((hl (bound-and-true-p hl-line-mode)))
    (when hl (hl-line-mode -1))
    (prog1
        (with-current-buffer (make-indirect-buffer (current-buffer) " *screenshot-clone" t t)
          (narrow-to-region beg end)
          (screenshot--setup-buffer)
          (buffer-face-set :family screenshot-font-family
                           :height (* 10 screenshot-font-size))
          (current-buffer))
      (when hl (hl-line-mode 1)))))

``` 
? (Changed `(clone-indirect-buffer " *screenshot-clone" nil t)` to `(make-indirect-buffer (current-buffer) " *screenshot-clone" t t)`)

**Comment by tecosaur** [comment]
That does look promising! Thanks for the suggestion, I've implemented it in 71d4da9cc2092522e2451e47b4e8dc4d9f7a5d82.

**Comment by Jake-Moss** [comment]
That works! Thank you!
If you don't mind me asking, whats the use of the secondary clone?
```diff
-        (with-current-buffer (clone-indirect-buffer " *screenshot-clone" nil t)
+        (with-current-buffer (make-indirect-buffer (current-buffer) " *screenshot-clone" t t)
+            (clone-indirect-buffer " *screenshot-clone" nil t)
```

**Comment by tecosaur** [comment]
the point of that is to show me that I should be more careful that I don't accidentally commit unintentional changes :stuck_out_tongue:
