### ISSUE TITLE
Confusion regarding transient 

### ISSUE THREAD

**Issue by dorneanu** [tecosaur/screenshot#15]
Hi, 

I think this is a great package. However, I don't know to actually activate the transient menu. Whenever I mark a region I'm asked to specify a file name, a scheme and then afterwards I'm asked to `C-c C-c` in order to take a screenshot. But then I need to actually drag the mouse around the region I want to have a screenshot from. And I don't get any other options to configure. 

Thanks in advance.

**Comment by dorneanu** [comment]
I just noticed (for whatever reason) I had an old version of `screenshot.el` locally installed. I'm using Doom Emacs and in my `packages.el` I do have:

> (package! screenshot :recipe (:host github :repo "tecosaur/screenshot"))

But ~/.emacs.d/.local/straight/repos/screenshot/screenshot.el contained like a really old version of it.  I just replaced the old content with the [new one](https://github.com/tecosaur/screenshot/blob/master/screenshot.el). But I know this is not the proper way to do it. 

Maybe you can point me into the right direction what went wrong with caching and the like.

**Comment by tecosaur** [comment]
You should be able to efficiently mark a region for a screenshot using Emacs/EVIL.

For everything else, you just need to use a recent version. `doom upgrade` should update packages too.
