### ISSUE TITLE
Support Windows users with ShareX

### ISSUE THREAD

**Issue by mplscorwin** [tecosaur/screenshot#3]
Hello.

[ShareX](https://github.com/ShareX/ShareX) is a GPLv3 screen-shot/capture/share tool for windows. 

Would you consider enabling support for this, perhaps with nested feature detecting checking window-version then executable find for sharex.exe?

I would be happy to try creating a patch for this if you might be inclined to include it.

Thanks for your work on this!

**Comment by tecosaur** [comment]
I like the idea of this working cross-platform.

If you think we can have this work well for windows with this, that would be great!
Please try making a patch if you get it working :slightly_smiling_face:

**Comment by tecosaur** [comment]
Any luck so far?

**Comment by tecosaur** [comment]
@mplscorwin how's it going?

**Comment by tecosaur** [comment]
@mplscorwin let me know if you ever get back to this.

**Comment by mplscorwin** [comment]
Sorry, never saw notifs for this (and forgot about it completely).  Easy enough to open a new PR if I have some code to go with it :)
