### ISSUE TITLE
Wrongly labeled config option

### ISSUE THREAD

**Issue by thomasheartman** [tecosaur/screenshot#5]
Hey! Great work in this package; it's a nice little quality of life improvement!

I just wanted to report what I believe is a typo (a copy-paste remnant, most likely), in the configuration: both the '-w' and '-W' options are labeled as 'minimum width', but I think the second should be 'maximum width'. The prompt and shorthand at least corroborate this and use 'Maximum width (columns)' and 'max-width' respectively.

This screenshot is of the source code, where the second block has a remaining "Minimum width" that should be "Maximum width".

![two configuration options for width, min width and max width](https://user-images.githubusercontent.com/17786332/112002148-e3618c00-8b1f-11eb-933d-9fd9419d2e36.png)

This concerns [line 405 in the source file](https://github.com/tecosaur/screenshot/blob/6825ec53d2fda060dc235ee7696c6920faf7287f/screenshot.el#L405).

**Comment by tecosaur** [comment]
Yep. That should be changed.

**Comment by thomasheartman** [comment]
Nice :smile: Do you want a PR for it? I'm happy to submit one if you wouldn't rather take care of it yourself.

**Comment by tecosaur** [comment]
Nah, it's fine, but thanks for offering.
