### ISSUE TITLE
Screenshot taking the buffer theme for non-text only version

### ISSUE THREAD

**Issue by zackteo** [tecosaur/screenshot#6]
![image](https://user-images.githubusercontent.com/7510179/112779120-9aa65780-9078-11eb-8798-355b55b51e61.png)
![image](https://user-images.githubusercontent.com/7510179/112779172-b01b8180-9078-11eb-9564-bfbd9d8f86d1.png)

When I toggle `-t` I get this difference in behaviour. The last I used your package, I managed to get the org-mode formatting with but with the same dark background as the border. 

I can't seem to identify what changed since then. Was playing around with the different flags but could not figure it out. 

Also, thanks for your package! It has been helping me out with university work

**Comment by tecosaur** [comment]
One thing that occurs to me as helpful that I could add, is disabling solarire mode for the screenshot.

However, the text-only mode *should* work. If you are able to bisect this that would be great.

**Comment by zackteo** [comment]
Not sure what you mean exactly by bisecting but tried to dig in to your past commits. Might be doing something wrong but doesn't seem to be something on your side. Tried to reset my doom emacs to see if it were that - but somehow doesn't seem to from there either (I might have done something wrong for this)

**Comment by zackteo** [comment]
Unless it was from updating imagemagick recently ...... 🤔  yeap i'm not too sure ><

**Comment by tecosaur** [comment]
> The last I used your package, I managed to get the org-mode formatting with but with the same dark background as the border.
> I can't seem to identify what changed since then

Sounds like it was working for you at some point, but then it broke at some other point. This is what `git bisect` is good for. You can see https://www.jwir3.com/git-bisect-gentle-introduction/ for an intro.

I'll get around to this eventually if you don't, I just don't know when :stuck_out_tongue:.

**Comment by tecosaur** [comment]
This may be fixed in f8204e82dc0c1158c401735d36a143e6f6d24cf5 if you're using solaire mode.
